// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUPFYIcTGNl4Neb8-uyZ5SIgxXvY991yI',
    appId: '1:1070117292933:web:7f90f48e982ef14c6652ec',
    messagingSenderId: '1070117292933',
    projectId: 'kustart-8006c',
    authDomain: 'kustart-8006c.firebaseapp.com',
    databaseURL: 'https://kustart-8006c-default-rtdb.firebaseio.com',
    storageBucket: 'kustart-8006c.appspot.com',
    measurementId: 'G-B3GVNYCBNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuZNGlCDbeopmrbG4dZ6TC3ijrUw4Pk7Y',
    appId: '1:1070117292933:android:a1a0db82aa1b2fae6652ec',
    messagingSenderId: '1070117292933',
    projectId: 'kustart-8006c',
    databaseURL: 'https://kustart-8006c-default-rtdb.firebaseio.com',
    storageBucket: 'kustart-8006c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDalU3syLkj_patxGTdEStnW65B5P4Q_W0',
    appId: '1:1070117292933:ios:ad1b4e3fe65530116652ec',
    messagingSenderId: '1070117292933',
    projectId: 'kustart-8006c',
    databaseURL: 'https://kustart-8006c-default-rtdb.firebaseio.com',
    storageBucket: 'kustart-8006c.appspot.com',
    iosBundleId: 'com.example.kustart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDalU3syLkj_patxGTdEStnW65B5P4Q_W0',
    appId: '1:1070117292933:ios:acdb20d899de42d86652ec',
    messagingSenderId: '1070117292933',
    projectId: 'kustart-8006c',
    databaseURL: 'https://kustart-8006c-default-rtdb.firebaseio.com',
    storageBucket: 'kustart-8006c.appspot.com',
    iosBundleId: 'com.example.kustart.RunnerTests',
  );
}
